### PR TITLE
QCA988X: 10.2.4: add firmware-5.bin_10.2.4.70.52

### PR DESCRIPTION
**Pull request by mrobbetts**
I've just updated the `ath988x` firmware to `10.2.4.70.52` from the upstream repo.

### CODE REVIEW

**Comment by wkennington** [comment]
Send this upstream to
http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git. I
don't actually maintain extra blobs here. This would benefit the larger
community anyway.

**Comment by mrobbetts** [comment]
@wkennington, do you occasionally somehow sync this to that repo, then? I'm new to Github and its various workflows, and I didn't see there was a direct connection between this and that, so I thought you must be pulling in commits by hand to here or so.

I can go upstream with this, anyhow.

**Comment by wkennington** [comment]
Yeah this repo is synced with upstream periodically and I dont make any
customizations here.

**Comment by wkennington** [comment]
This should be up to date now.

**Pull request closed without merging**
